version: 0.1
log:
  fields:
    service: registry

storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry

http:
  addr: :5000 # ChangeMe
  headers:
    X-Content-Type-Options: [nosniff]
